apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  namespace: monitoring
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  prometheus.yml: |
    global:
      {{- toYaml .Values.prometheus.config.global | nindent 6 }}
    
    rule_files:
      {{- toYaml .Values.prometheus.config.rule_files | nindent 6 }}
    
    scrape_configs:
      {{- toYaml .Values.prometheus.config.scrape_configs | nindent 6 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-rules
  namespace: monitoring
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  basic.yml: |
    groups:
      - name: basic
        rules:
          - alert: PrometheusDown
            expr: up{job="prometheus"} == 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Prometheus server is down"
              description: "Prometheus server has been down for more than 5 minutes."
          
          - alert: HighMemoryUsage
            expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.85
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage detected"
              description: "Memory usage is above 85% for more than 10 minutes."
          
          - alert: HighCPUUsage
            expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage detected"
              description: "CPU usage is above 80% for more than 10 minutes."