# Service Account pour automation namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: automation-sa
  namespace: automation
  labels:
    app.kubernetes.io/name: automation-service-account
    app.kubernetes.io/component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: automation
  name: automation-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: automation-binding
  namespace: automation
subjects:
- kind: ServiceAccount
  name: automation-sa
  namespace: automation
roleRef:
  kind: Role
  name: automation-role
  apiGroup: rbac.authorization.k8s.io
---
# Service Account pour databases namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: databases-sa
  namespace: databases
  labels:
    app.kubernetes.io/name: databases-service-account
    app.kubernetes.io/component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: databases
  name: databases-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: databases-binding
  namespace: databases
subjects:
- kind: ServiceAccount
  name: databases-sa
  namespace: databases
roleRef:
  kind: Role
  name: databases-role
  apiGroup: rbac.authorization.k8s.io
---
# Service Account pour cache namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache-sa
  namespace: cache
  labels:
    app.kubernetes.io/name: cache-service-account
    app.kubernetes.io/component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cache
  name: cache-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cache-binding
  namespace: cache
subjects:
- kind: ServiceAccount
  name: cache-sa
  namespace: cache
roleRef:
  kind: Role
  name: cache-role
  apiGroup: rbac.authorization.k8s.io
---
# Service Account pour monitoring namespace (extension de l'existant)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring-service-account
    app.kubernetes.io/component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-cluster-binding
subjects:
- kind: ServiceAccount
  name: monitoring-sa
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: monitoring-cluster-role
  apiGroup: rbac.authorization.k8s.io