---
- name: Configuration de base du serveur
  hosts: all
  become: yes
  tasks:
    - name: Mise à jour du cache des paquets
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installation des paquets de base
      apt:
        name:
          - curl
          - wget
          - git
          - vim
        state: present