# =============================================================================
# JOBS DE DÉPLOIEMENT ANSIBLE (VERSION REFACTORISÉE)  
# =============================================================================

# Déploiement Ansible dev
ansible_dev:
  extends: 
    - .ansible_deploy_dev
  variables:
    PLAYBOOK_PATH: "playbooks/setup.yml"
  dependencies:
    - apply_dev
  tags:
    - ansible