# =============================================================================
# JOBS DE DÉPLOIEMENT KUBERNETES
# =============================================================================
# Description : Jobs pour le setup et la validation des namespaces K8s + Prometheus
# Version     : 1.1.0 - Ajout déploiement Prometheus
# =============================================================================

# Setup des namespaces en dev
kubernetes_setup_dev:
  extends: .kubernetes_setup_dev
  stage: kubernetes
  dependencies:
    - apply_dev
  needs:
    - job: apply_dev
      artifacts: true

# Setup des namespaces en prod
kubernetes_setup_prod:
  extends: .kubernetes_setup_prod
  stage: kubernetes
  dependencies:
    - apply_prod
  needs:
    - job: apply_prod
      artifacts: true

# Validation des namespaces (peut être lancé indépendamment)
kubernetes_validate:
  extends: .kubernetes_validate
  stage: kubernetes
  variables:
    MANIFEST_PATH: "kubernetes/manifests"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  needs: []

# 🆕 Déploiement Prometheus en dev
deploy_prometheus_dev:
  extends: .kubernetes_deploy_prometheus_dev
  stage: kubernetes
  dependencies:
    - kubernetes_setup_dev
  needs:
    - job: kubernetes_setup_dev
      artifacts: true

# 🆕 Déploiement Prometheus en prod
deploy_prometheus_prod:
  extends: .kubernetes_deploy_prometheus_prod
  stage: kubernetes
  dependencies:
    - kubernetes_setup_prod
  needs:
    - job: kubernetes_setup_prod
      artifacts: true

# Test de connectivité des namespaces
kubernetes_test:
  extends: .kubernetes_test
  stage: kubernetes
  variables:
    TEST_NAMESPACE: "automation"
  dependencies:
    - kubernetes_setup_dev
    - kubernetes_setup_prod
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
  allow_failure: true